global using Xunit;
global using NSubstitute;
global using NSubstitute.ExceptionExtensions;
global using FluentAssertions;
global using Microsoft.AspNetCore.Mvc;
global using ProjectTasksManager.Controllers;
global using ProjectTasksManager.DTOs.User;
global using ProjectTasksManager.Models;
global using ProjectTasksManager.Data;
global using ProjectTasksManager.Repositories.Interfaces;
global using ProjectTasksManager.Services.Interfaces;
global using ProjectTasksManager.Services;
global using Task = System.Threading.Tasks.Task;
